
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yassine
 */
public class Affectation1 extends javax.swing.JFrame {

    /**
     * Creates new form Affectation1
     */
    public Affectation1() {
        initComponents();
        setTitle("Affectation");
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_aj = new javax.swing.JButton();
        btn_retour = new javax.swing.JButton();
        btn_cons_stock = new javax.swing.JButton();
        btn_cons_stock1 = new javax.swing.JButton();
        btn_imprimer_etat = new javax.swing.JButton();
        btn_modifier_stock = new javax.swing.JButton();
        la_aff = new javax.swing.JLabel();
        btn_imprimer_etat2 = new javax.swing.JButton();
        btn_quitter1 = new javax.swing.JButton();
        btn_Taffe = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_aj.setBackground(new java.awt.Color(67, 174, 76));
        btn_aj.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Ajouter.png")); // NOI18N
        btn_aj.setText("Ajouter Téléphone");
        btn_aj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajActionPerformed(evt);
            }
        });

        btn_retour.setBackground(new java.awt.Color(67, 174, 76));
        btn_retour.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Back.png")); // NOI18N
        btn_retour.setText("Retour");
        btn_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retourActionPerformed(evt);
            }
        });

        btn_cons_stock.setBackground(new java.awt.Color(67, 174, 76));
        btn_cons_stock.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\consulter.png")); // NOI18N
        btn_cons_stock.setText("Consulter Stock");
        btn_cons_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cons_stockActionPerformed(evt);
            }
        });

        btn_cons_stock1.setBackground(new java.awt.Color(67, 174, 76));
        btn_cons_stock1.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Search.png")); // NOI18N
        btn_cons_stock1.setText("Rechercher");
        btn_cons_stock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cons_stock1ActionPerformed(evt);
            }
        });

        btn_imprimer_etat.setBackground(new java.awt.Color(67, 174, 76));
        btn_imprimer_etat.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\statistics.png")); // NOI18N
        btn_imprimer_etat.setText("Consulter Statistique");
        btn_imprimer_etat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimer_etatActionPerformed(evt);
            }
        });

        btn_modifier_stock.setBackground(new java.awt.Color(67, 174, 76));
        btn_modifier_stock.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\editer.png")); // NOI18N
        btn_modifier_stock.setText("Modifier Stock");
        btn_modifier_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_stockActionPerformed(evt);
            }
        });

        la_aff.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        la_aff.setForeground(new java.awt.Color(67, 174, 76));
        la_aff.setText("Affectation");

        btn_imprimer_etat2.setBackground(new java.awt.Color(67, 174, 76));
        btn_imprimer_etat2.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\PDF.png")); // NOI18N
        btn_imprimer_etat2.setText("Imprimer Etat");
        btn_imprimer_etat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimer_etat2ActionPerformed(evt);
            }
        });

        btn_quitter1.setBackground(new java.awt.Color(67, 174, 76));
        btn_quitter1.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\quitter.png")); // NOI18N
        btn_quitter1.setText("Quitter");
        btn_quitter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitter1ActionPerformed(evt);
            }
        });

        btn_Taffe.setBackground(new java.awt.Color(67, 174, 76));
        btn_Taffe.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Home-.png")); // NOI18N
        btn_Taffe.setText("Accueil");
        btn_Taffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaffeActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(la_aff, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 499, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_aj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_retour, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_imprimer_etat2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(202, 202, 202)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_quitter1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cons_stock1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cons_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_imprimer_etat, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_modifier_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Taffe, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(la_aff, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aj, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_imprimer_etat, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cons_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btn_imprimer_etat2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cons_stock1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_modifier_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_quitter1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Taffe, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Affectation a=new Affectation();
        a.setVisible(true);
    }//GEN-LAST:event_btn_ajActionPerformed

    private void btn_cons_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cons_stockActionPerformed
         this.setVisible(false);
        Affectation a=new Affectation();
        a.setVisible(true);
    }//GEN-LAST:event_btn_cons_stockActionPerformed

    private void btn_imprimer_etatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimer_etatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imprimer_etatActionPerformed

    private void btn_modifier_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_stockActionPerformed
         this.setVisible(false);
        Affectation a=new Affectation();
        a.setVisible(true);
    }//GEN-LAST:event_btn_modifier_stockActionPerformed

    private void btn_imprimer_etat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimer_etat2ActionPerformed
       this.setVisible(false);
        Affectation a=new Affectation();
        a.setVisible(true);
    }//GEN-LAST:event_btn_imprimer_etat2ActionPerformed

    private void btn_cons_stock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cons_stock1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cons_stock1ActionPerformed

    private void btn_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retourActionPerformed
         this.setVisible(false);
        home h=new home();
        h.setVisible(true);
    }//GEN-LAST:event_btn_retourActionPerformed

    private void btn_quitter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitter1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_quitter1ActionPerformed

    private void btn_TaffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaffeActionPerformed
        Fonct AF= new Fonct();
        AF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_TaffeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Affectation1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Affectation1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Affectation1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Affectation1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Affectation1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Taffe;
    private javax.swing.JButton btn_aj;
    private javax.swing.JButton btn_cons_stock;
    private javax.swing.JButton btn_cons_stock1;
    private javax.swing.JButton btn_imprimer_etat;
    private javax.swing.JButton btn_imprimer_etat2;
    private javax.swing.JButton btn_modifier_stock;
    private javax.swing.JButton btn_quitter1;
    private javax.swing.JButton btn_retour;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel la_aff;
    // End of variables declaration//GEN-END:variables
}
