/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author yassine
 */
public class AjouterAuDernierArr extends javax.swing.JFrame {
    Statement stat=null;
    MysqlConnect  maConnexion=new MysqlConnect();

    /**
     * Creates new form AjouterAuDernierArr
     */
    public AjouterAuDernierArr() {
        initComponents();
        setTitle("Dernier Arrivage");
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laDa = new javax.swing.JLabel();
        laTypeA = new javax.swing.JLabel();
        laNS = new javax.swing.JLabel();
        laAM = new javax.swing.JLabel();
        TF_idS1 = new javax.swing.JTextField();
        TF_NS1 = new javax.swing.JTextField();
        TF_addM = new javax.swing.JTextField();
        btn_retour = new javax.swing.JButton();
        btn_ajouter = new javax.swing.JButton();
        laTypeA1 = new javax.swing.JLabel();
        TF_TypeAPP1 = new javax.swing.JTextField();
        btn_Taffe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        laDa.setBackground(new java.awt.Color(67, 174, 76));
        laDa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        laDa.setForeground(new java.awt.Color(67, 174, 76));
        laDa.setText("Ajouter  Au Dernier Arrivage");

        laTypeA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laTypeA.setText("Id");

        laNS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laNS.setText("N ° de Série");

        laAM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laAM.setText("Adresse Mac");

        btn_retour.setBackground(new java.awt.Color(67, 174, 76));
        btn_retour.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_retour.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Back.png")); // NOI18N
        btn_retour.setText("Retour");
        btn_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retourActionPerformed(evt);
            }
        });

        btn_ajouter.setBackground(new java.awt.Color(67, 174, 76));
        btn_ajouter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_ajouter.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Ajouter.png")); // NOI18N
        btn_ajouter.setText("Ajouter");
        btn_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouterActionPerformed(evt);
            }
        });

        laTypeA1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laTypeA1.setText("Type D'appareil");

        btn_Taffe.setBackground(new java.awt.Color(67, 174, 76));
        btn_Taffe.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Home-.png")); // NOI18N
        btn_Taffe.setText("Accueil");
        btn_Taffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaffeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(laDa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(laNS)
                            .addComponent(laTypeA)
                            .addComponent(laAM))
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_addM, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_NS1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TF_TypeAPP1)
                                .addComponent(TF_idS1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(btn_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(btn_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(btn_Taffe, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 116, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(368, 368, 368)
                    .addComponent(laTypeA1)
                    .addContainerGap(547, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(laDa)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laTypeA)
                    .addComponent(TF_idS1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(TF_TypeAPP1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laNS)
                    .addComponent(TF_NS1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laAM)
                    .addComponent(TF_addM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_Taffe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(171, 171, 171)
                    .addComponent(laTypeA1)
                    .addContainerGap(424, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouterActionPerformed
        // TODO add your handling code here:
        String typeApp= TF_TypeAPP1.getText();
        String addM= TF_addM.getText();
        String serie= TF_NS1.getText();
        String idS1= TF_idS1.getText();
        
        
        
           
           
           
        
      String requette="INSERT INTO dernierarr VALUES('"+idS1+"','"+typeApp+"','"+serie+"','"+addM+"') ";
        try{
        
        stat=MysqlConnect.ConnectDB().createStatement();
       // JOptionPane.showMessageDialog(null, "req succes");
        
     // stat.executeQuery(requete);
        stat.executeUpdate(requette);
        JOptionPane.showMessageDialog(null, "ajouté avce succes");
       TF_idS1.setText("");
        TF_addM.setText("");
        TF_NS1.setText("");
        TF_TypeAPP1.setText("");
        
        }catch(SQLException ex){
        System.err.println(ex);
       
         JOptionPane.showMessageDialog(null, " Erreur ajout  à la BD");
       /*TF_Type.setText("");
        TF_adresseM.setText("");
        TF_titulaire.setText("");
        TF_Extention.setText("");
        TF_serie.setText("");*/
    }//GEN-LAST:event_btn_ajouterActionPerformed
    }
    private void btn_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retourActionPerformed

        
// TODO add your handling code here:
        
        
            this.setVisible(false);
        DernierArrivage1 d=new DernierArrivage1();
        d.setVisible(true);
        
        
    }//GEN-LAST:event_btn_retourActionPerformed

    private void btn_TaffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaffeActionPerformed
        Fonct AF= new Fonct();
        AF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_TaffeActionPerformed

    /**
     * @param args the command line arguments
     */

    /**
     *
     * @param args
     */
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterAuDernierArr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterAuDernierArr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterAuDernierArr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterAuDernierArr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterAuDernierArr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_NS1;
    private javax.swing.JTextField TF_TypeAPP1;
    private javax.swing.JTextField TF_addM;
    private javax.swing.JTextField TF_idS1;
    private javax.swing.JButton btn_Taffe;
    private javax.swing.JButton btn_ajouter;
    private javax.swing.JButton btn_retour;
    private javax.swing.JLabel laAM;
    private javax.swing.JLabel laDa;
    private javax.swing.JLabel laNS;
    private javax.swing.JLabel laTypeA;
    private javax.swing.JLabel laTypeA1;
    // End of variables declaration//GEN-END:variables
}
