
import java.sql.*;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yassine
 */
public class Ajouter extends javax.swing.JFrame {
    Statement stat=null;
    MysqlConnect  maConnexion=new MysqlConnect();
    
    
    
    
    
    

    /**
     * Creates new form Ajouter
     */
    public Ajouter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        laAdresseM = new javax.swing.JLabel();
        laSerie = new javax.swing.JLabel();
        laTitulaire = new javax.swing.JLabel();
        laExtention = new javax.swing.JLabel();
        laType = new javax.swing.JLabel();
        TF_adresseM = new javax.swing.JTextField();
        TF_serie = new javax.swing.JTextField();
        TF_titulaire = new javax.swing.JTextField();
        TF_Extention = new javax.swing.JTextField();
        TF_Type = new javax.swing.JTextField();
        btn_ajouter = new javax.swing.JButton();
        btn_retour = new javax.swing.JButton();
        btn_Taffe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Ajouter");

        laAdresseM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laAdresseM.setText("Adresse Mac");

        laSerie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laSerie.setText("N ° de série");

        laTitulaire.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laTitulaire.setText("Titulaire");

        laExtention.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laExtention.setText("Extention");

        laType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laType.setText("Type");

        btn_ajouter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ajouter.setText("Ajouter");
        btn_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouterActionPerformed(evt);
            }
        });

        btn_retour.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_retour.setText("Retour");
        btn_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retourActionPerformed(evt);
            }
        });

        btn_Taffe.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Home-.png")); // NOI18N
        btn_Taffe.setText("Accueil");
        btn_Taffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaffeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(laAdresseM)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(laType)
                                .addComponent(laTitulaire)
                                .addComponent(laSerie)
                                .addComponent(laExtention)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(btn_Taffe, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addGap(96, 96, 96)
                        .addComponent(btn_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_retour, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(TF_adresseM)
                    .addComponent(TF_serie)
                    .addComponent(TF_titulaire)
                    .addComponent(TF_Extention)
                    .addComponent(TF_Type, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addGap(251, 251, 251))
            .addGroup(layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(laAdresseM, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addComponent(laSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(laTitulaire, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addComponent(laExtention, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(374, 374, 374))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TF_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TF_adresseM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)))
                        .addGap(52, 52, 52))
                    .addComponent(TF_titulaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(TF_Extention, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(laType, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_ajouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Taffe, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_retour, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addGap(118, 118, 118))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retourActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Fonct f=new Fonct();
        f.setVisible(true);
    }//GEN-LAST:event_btn_retourActionPerformed

    private void btn_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouterActionPerformed
        // TODO add your handling code here:
        
        String type= TF_Type.getText();
        String adresseM= TF_adresseM.getText();
        String titulaire= TF_titulaire.getText();
        String extention= TF_Extention.getText();
        String serie= TF_serie.getText();
        
        
        //String requete="INSERT INTO telvoixip(Type,AdresseMac,Titulaire,Extention,serie)VALUES('"+type+"','"+adresseM+"','"+titulaire+"','"+extention+"','"+serie+"') ";
       String requette="INSERT INTO telvoixip VALUES('"+type+"','"+adresseM+"','"+titulaire+"','"+extention+"','"+serie+"')";
        try{
        
        stat=MysqlConnect.ConnectDB().createStatement();
        JOptionPane.showMessageDialog(null, "req succes");
        
     // stat.executeQuery(requete);
        stat.executeUpdate(requette);
        JOptionPane.showMessageDialog(null, "ajouté avce succes");
        
       
        TF_Type.setText("");
        TF_adresseM.setText("");
        TF_titulaire.setText("");
        TF_Extention.setText("");
        TF_serie.setText("");
        
        
        }catch(SQLException ex){
        System.err.println(ex);
       
         JOptionPane.showMessageDialog(null, " Erreur ajout  à la BD");
        TF_Type.setText("");
        TF_adresseM.setText("");
        TF_titulaire.setText("");
        TF_Extention.setText("");
        TF_serie.setText("");
        }
    }//GEN-LAST:event_btn_ajouterActionPerformed

    private void btn_TaffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaffeActionPerformed
        Fonct AF= new Fonct();
        AF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_TaffeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajouter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_Extention;
    private javax.swing.JTextField TF_Type;
    private javax.swing.JTextField TF_adresseM;
    private javax.swing.JTextField TF_serie;
    private javax.swing.JTextField TF_titulaire;
    private javax.swing.JButton btn_Taffe;
    private javax.swing.JButton btn_ajouter;
    private javax.swing.JButton btn_retour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel laAdresseM;
    private javax.swing.JLabel laExtention;
    private javax.swing.JLabel laSerie;
    private javax.swing.JLabel laTitulaire;
    private javax.swing.JLabel laType;
    // End of variables declaration//GEN-END:variables
}
