/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author yassine
 */
public class AjouterDernierArrivage extends javax.swing.JFrame {

    Statement stat=null;
    MysqlConnect  maConnexion=new MysqlConnect();
    
    /**
     * Creates new form DernierArrivage
     */
   
    public AjouterDernierArrivage() {
        initComponents();
        setTitle(" ajouter au Dernier Arrivage");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laDerArrivage = new javax.swing.JLabel();
        laDernierArrivage = new javax.swing.JLabel();
        laSerie = new javax.swing.JLabel();
        laAdresseMa = new javax.swing.JLabel();
        TF_id = new javax.swing.JTextField();
        TF_NS1 = new javax.swing.JTextField();
        TF_addM = new javax.swing.JTextField();
        btn_retour = new javax.swing.JButton();
        btn_Ajouter1 = new javax.swing.JButton();
        laid = new javax.swing.JLabel();
        TF_TypeAPP1 = new javax.swing.JTextField();
        btn_Taffe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        laDerArrivage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        laDerArrivage.setText("Ajouter au Dernier Arrivage");

        laDernierArrivage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laDernierArrivage.setText("Type D'appareil");

        laSerie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laSerie.setText("N ° de  Série");

        laAdresseMa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laAdresseMa.setText("Adresse Mac");

        btn_retour.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_retour.setText("Retour");
        btn_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retourActionPerformed(evt);
            }
        });

        btn_Ajouter1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Ajouter1.setText("Ajouter");
        btn_Ajouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ajouter1ActionPerformed(evt);
            }
        });

        laid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laid.setText("id");

        btn_Taffe.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Home-.png")); // NOI18N
        btn_Taffe.setText("Accueil");
        btn_Taffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaffeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(laDerArrivage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(laSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(laDernierArrivage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(laAdresseMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(laid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TF_NS1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(TF_addM)
                            .addComponent(TF_id)
                            .addComponent(TF_TypeAPP1))))
                .addGap(322, 322, 322))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_Taffe, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(342, 342, 342)
                    .addComponent(btn_Ajouter1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(482, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(laDerArrivage)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laid)
                    .addComponent(TF_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(laDernierArrivage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TF_TypeAPP1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(laSerie)
                    .addComponent(TF_NS1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(laAdresseMa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(TF_addM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addComponent(btn_Taffe, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btn_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(469, Short.MAX_VALUE)
                    .addComponent(btn_Ajouter1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(91, 91, 91)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retourActionPerformed

        // TODO add your handling code here:
        this.setVisible(false);
        Fonct f=new Fonct();
        f.setVisible(true);

    }//GEN-LAST:event_btn_retourActionPerformed

    private void btn_Ajouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ajouter1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_Ajouter1ActionPerformed

    private void btn_TaffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaffeActionPerformed
        Fonct AF= new Fonct();
        AF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_TaffeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterDernierArrivage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterDernierArrivage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterDernierArrivage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterDernierArrivage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()) {
            public void run() {
                new AjouterDernierArrivage().setVisible(true);
            }}
        });
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_NS1;
    private javax.swing.JTextField TF_TypeAPP1;
    private javax.swing.JTextField TF_addM;
    private javax.swing.JTextField TF_id;
    private javax.swing.JButton btn_Ajouter1;
    private javax.swing.JButton btn_Taffe;
    private javax.swing.JButton btn_retour;
    private javax.swing.JLabel laAdresseMa;
    private javax.swing.JLabel laDerArrivage;
    private javax.swing.JLabel laDernierArrivage;
    private javax.swing.JLabel laSerie;
    private javax.swing.JLabel laid;
    // End of variables declaration//GEN-END:variables
}
}