/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author yassine
 */
public class AjouterTelAncienStock extends javax.swing.JFrame {
    Statement stat=null;
    MysqlConnect  maConnexion=new MysqlConnect();

    /**
     * Creates new form AjouterTelAncienStock
     */
    public AjouterTelAncienStock() {
        initComponents();
        getContentPane().setBackground(Color.white);
        setTitle("ajouter à l'ancien stock");
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laAncienStock = new javax.swing.JLabel();
        btn_Retour = new javax.swing.JButton();
        bnt_AjAncStock1 = new javax.swing.JButton();
        btn_Taffe = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TF_IdTel = new javax.swing.JTextField();
        TF_NS = new javax.swing.JTextField();
        laAdresseM = new javax.swing.JLabel();
        laNserie = new javax.swing.JLabel();
        laIdTel = new javax.swing.JLabel();
        TF_AddM = new javax.swing.JTextField();
        TF_typeApp1 = new javax.swing.JTextField();
        laTypeAp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        laAncienStock.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        laAncienStock.setForeground(new java.awt.Color(67, 174, 76));
        laAncienStock.setText("Ajouter à l'ancien Stock");

        btn_Retour.setBackground(new java.awt.Color(67, 174, 76));
        btn_Retour.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_Retour.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Back.png")); // NOI18N
        btn_Retour.setText("Retour");
        btn_Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RetourActionPerformed(evt);
            }
        });

        bnt_AjAncStock1.setBackground(new java.awt.Color(67, 174, 76));
        bnt_AjAncStock1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bnt_AjAncStock1.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Ajouter.png")); // NOI18N
        bnt_AjAncStock1.setText("Ajouter");
        bnt_AjAncStock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_AjAncStock1ActionPerformed(evt);
            }
        });

        btn_Taffe.setBackground(new java.awt.Color(67, 174, 76));
        btn_Taffe.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Home-.png")); // NOI18N
        btn_Taffe.setText("Accueil");
        btn_Taffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaffeActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 174, 76), 2));

        laAdresseM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laAdresseM.setText("Adresse Mac");

        laNserie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laNserie.setText("N ° de Série");

        laIdTel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laIdTel.setText("ID tel");

        laTypeAp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        laTypeAp.setText("Type D'appareil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(laTypeAp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(laNserie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(laAdresseM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(laIdTel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TF_NS)
                    .addComponent(TF_IdTel)
                    .addComponent(TF_AddM)
                    .addComponent(TF_typeApp1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(laIdTel)
                    .addComponent(TF_IdTel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(laTypeAp)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_typeApp1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(laNserie)
                    .addComponent(TF_NS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(laAdresseM)
                    .addComponent(TF_AddM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(bnt_AjAncStock1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(btn_Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btn_Taffe, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(laAncienStock)))
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(laAncienStock, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnt_AjAncStock1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Taffe, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RetourActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AncienStock1 d=new AncienStock1();
        d.setVisible(true);
        
    }//GEN-LAST:event_btn_RetourActionPerformed

    private void bnt_AjAncStock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_AjAncStock1ActionPerformed
        // TODO add your handling code here:
        
        
        
        String idS=TF_IdTel.getText();
        String typeApp= TF_typeApp1.getText();
        String serie= TF_NS.getText();
        String addM= TF_AddM.getText();
       
        
        
        String requette="INSERT INTO ancienstock VALUES('"+idS+"','"+typeApp+"','"+serie+"','"+addM+"')";
        try{
        
        stat=MysqlConnect.ConnectDB().createStatement();
       // JOptionPane.showMessageDialog(null, "req succes");
        
     
        stat.executeUpdate(requette);
        JOptionPane.showMessageDialog(null, "ajouté avce succes");
        
       
        TF_IdTel.setText("");
        TF_AddM.setText("");
        TF_typeApp1.setText("");
        TF_NS.setText("");

        }catch(SQLException e){
       
       
         JOptionPane.showMessageDialog(null," Erreur ajout  à la BD"+e+"");
        TF_IdTel.setText("");
        TF_AddM.setText("");
        TF_typeApp1.setText("");
        TF_NS.setText("");
        }
    }//GEN-LAST:event_bnt_AjAncStock1ActionPerformed

    private void btn_TaffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaffeActionPerformed
        Fonct AF= new Fonct();
        AF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_TaffeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterTelAncienStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterTelAncienStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterTelAncienStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterTelAncienStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterTelAncienStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_AddM;
    private javax.swing.JTextField TF_IdTel;
    private javax.swing.JTextField TF_NS;
    private javax.swing.JTextField TF_typeApp1;
    private javax.swing.JButton bnt_AjAncStock1;
    private javax.swing.JButton btn_Retour;
    private javax.swing.JButton btn_Taffe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel laAdresseM;
    private javax.swing.JLabel laAncienStock;
    private javax.swing.JLabel laIdTel;
    private javax.swing.JLabel laNserie;
    private javax.swing.JLabel laTypeAp;
    // End of variables declaration//GEN-END:variables
}
