
import java.awt.*;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import BDD.Parameter;
import BDD.ResultSetTableModel;
import BDD.BDD;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import BDD.BDD;
import java.text.MessageFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yassine
 */
public class AncienStock extends javax.swing.JFrame {
     Statement stat=null;
    MysqlConnect  maConnexion=new MysqlConnect();
    Connection conn=null;
    PreparedStatement pst=null;
   // ResultSet rs=null;
    ResultSet rs;
    BDD db;
   
    

    /**
     * Creates new form AncienStock
     */
    
    
    public AncienStock()  {
        setTitle("Ancien Stock");
        initComponents();
         db = new BDD(new Parameter().HOST_DB, new Parameter().USERNAME_DB, new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        
        getContentPane().setBackground(Color.white);
        
         
      
        
   DefaultTableModel model= new DefaultTableModel();
   model.addColumn("idS");
   model.addColumn("TypeApp");
   model.addColumn("Nserie");
   model.addColumn("AddM");
   
   
   
   TableAncienStock.setModel(model);
   String requette="select * from ancienstock";
   try{
       
        stat=MysqlConnect.ConnectDB().createStatement();
        ResultSet rs=stat.executeQuery(requette);
        while(rs.next()){
        model.addRow(new Object[]{rs.getInt("idS"),rs.getString("TypeAPP"),rs.getString("NSerie"),rs.getString("AddM")} );
        }
         
   }catch(SQLException ex){
       JOptionPane.showMessageDialog(null, ex);
       
   };
   
   }
     public void table() {
        String t[] = {"idS","TypeApp","Nserie","AddM"};
        rs = db.querySelect(t, "ancienstock");
        TableAncienStock.setModel(new ResultSetTableModel(rs));
    }
     void actualiser() {
        txt_idTel.setText("");
        txt_typeA.setText("");
        txt_numS.setText("");
        txt_addM.setText("");}

    
    public void toExcel(JTable table, File file){
		try{
			TableModel model = table.getModel();
			FileWriter excel = new FileWriter(file);

			for(int i = 0; i < model.getColumnCount(); i++){
				excel.write(model.getColumnName(i) + "\t");
			}

			excel.write("\n");

			for(int i=0; i< model.getRowCount(); i++) {
				for(int j=0; j < model.getColumnCount(); j++) {
					excel.write(model.getValueAt(i,j).toString()+"\t");
				}
				excel.write("\n");
			}

			excel.close();
		}catch(IOException e){ System.out.println(e); }
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laAs = new javax.swing.JLabel();
        btn_retour = new javax.swing.JButton();
        btn_supprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAncienStock = new javax.swing.JTable();
        btn_update = new javax.swing.JButton();
        btn_inserer = new javax.swing.JButton();
        btnJtable = new javax.swing.JButton();
        btn_ExportExcl = new javax.swing.JButton();
        btn_Taffe = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_addM = new javax.swing.JTextField();
        txt_numS = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_typeA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_idTel = new javax.swing.JTextField();
        btn_ExportPdf = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        laAs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        laAs.setForeground(new java.awt.Color(67, 174, 76));
        laAs.setText(" Ancien Stock");

        btn_retour.setBackground(new java.awt.Color(67, 174, 76));
        btn_retour.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Back.png")); // NOI18N
        btn_retour.setText("Retour");
        btn_retour.setFocusable(false);
        btn_retour.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_retour.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retourActionPerformed(evt);
            }
        });

        btn_supprimer.setBackground(new java.awt.Color(67, 174, 76));
        btn_supprimer.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\poubelle.png")); // NOI18N
        btn_supprimer.setText("Supprimer");
        btn_supprimer.setFocusable(false);
        btn_supprimer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_supprimer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimerActionPerformed(evt);
            }
        });

        TableAncienStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Type appareil", "Numéro de série", "Adresse Mac", "Title 4", "Title 5"
            }
        ));
        TableAncienStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableAncienStockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableAncienStock);

        btn_update.setBackground(new java.awt.Color(67, 174, 76));
        btn_update.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\editer.png")); // NOI18N
        btn_update.setText("Modifier");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_inserer.setBackground(new java.awt.Color(67, 174, 76));
        btn_inserer.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Ajouter.png")); // NOI18N
        btn_inserer.setText("Ajouter");
        btn_inserer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insererActionPerformed(evt);
            }
        });

        btnJtable.setBackground(new java.awt.Color(67, 174, 76));
        btnJtable.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\transfrer.png")); // NOI18N
        btnJtable.setText("Affecter");
        btnJtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJtableActionPerformed(evt);
            }
        });

        btn_ExportExcl.setBackground(new java.awt.Color(67, 174, 76));
        btn_ExportExcl.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Excel.png")); // NOI18N
        btn_ExportExcl.setText("Export Excel");
        btn_ExportExcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExportExclActionPerformed(evt);
            }
        });

        btn_Taffe.setBackground(new java.awt.Color(67, 174, 76));
        btn_Taffe.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Home-.png")); // NOI18N
        btn_Taffe.setText("Accueil");
        btn_Taffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaffeActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 174, 76), 2));

        jLabel2.setText("Num Serie");

        jLabel4.setText("idTel");

        jLabel1.setText("TypeApp");

        jLabel3.setText("Adresse Mac");

        txt_idTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idTelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_addM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(114, 114, 114))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(88, 88, 88)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_idTel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_typeA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_numS, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txt_idTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_typeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_numS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_addM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btn_ExportPdf.setBackground(new java.awt.Color(67, 174, 76));
        btn_ExportPdf.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\PDF.png")); // NOI18N
        btn_ExportPdf.setText("Export PDF");
        btn_ExportPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExportPdfActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(btn_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btn_Taffe, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btn_inserer, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnJtable, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ExportExcl)
                        .addGap(28, 28, 28)
                        .addComponent(btn_ExportPdf)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(342, 342, 342))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(laAs)
                        .addGap(396, 396, 396))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(laAs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_inserer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnJtable, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_ExportExcl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_ExportPdf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Taffe, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1025, 707));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retourActionPerformed
        this.setVisible(false);
        AncienStock1 a=new AncienStock1();
        a.setVisible(true);
    
      
    }//GEN-LAST:event_btn_retourActionPerformed

    private void btn_supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimerActionPerformed
        // TODO add your handling code here:
       
      
        String id = String.valueOf(TableAncienStock.getValueAt(TableAncienStock.getSelectedRow(),0));
        if (JOptionPane.showConfirmDialog(this, "Voulez vraiment suprimer!!"," Avertissement", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("ancienstock", "idS=" + id);
        } else {
            return;
        }
        table();
        actualiser();
         
      
    }//GEN-LAST:event_btn_supprimerActionPerformed

    private void TableAncienStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableAncienStockMouseClicked
        // TODO add your handling code here:
     txt_idTel.setText(String.valueOf(TableAncienStock.getValueAt(TableAncienStock.getSelectedRow(),0)));
     txt_typeA.setText(String.valueOf(TableAncienStock.getValueAt(TableAncienStock.getSelectedRow(), 1)));
     txt_numS.setText(String.valueOf(TableAncienStock.getValueAt(TableAncienStock.getSelectedRow(),2)));
     txt_addM.setText(String.valueOf(TableAncienStock.getValueAt(TableAncienStock.getSelectedRow(),3)));
 
    }//GEN-LAST:event_TableAncienStockMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        /* rs=stat.executeQuery("select * from ancienstock");
       TableAncienStock.setModel(DbUtils.resultSetToTableModel(rs));*/
        
        
        if (txt_idTel.getText().equals("") || txt_typeA.getText().equals("") || txt_numS.getText().equals("")
                
                || txt_addM.getText().equals("") 
                ) {
            JOptionPane.showMessageDialog(this, "SVP entrer les informations complete");
        } else {
                  String[] colon = {"idS","typeApp","Nserie","AddM"};
              String[] inf = {txt_idTel.getText(), txt_typeA.getText(), txt_numS.getText(),txt_addM.getText()};
            String idS = String.valueOf(TableAncienStock.getValueAt(TableAncienStock.getSelectedRow(),0));
            System.out.println(db.queryUpdate("ancienstock", colon, inf, "idS='"+ idS+"'"));
            JOptionPane.showMessageDialog(this, "Modifié avec succès");
            table();
            actualiser();
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_insererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insererActionPerformed
       
          if (txt_idTel.getText().equals("") ||txt_typeA.getText().equals("") || txt_numS.getText().equals("")
                || txt_addM.getText().equals("") 
                ) {
            JOptionPane.showMessageDialog(this, "Veuillez Remplir tous les champs");
        } else {
            String[] colon = {"idS","TypeApp","Nserie","AddM"};
            String[] inf = {txt_idTel.getText(), txt_typeA.getText(), txt_numS.getText(),txt_addM.getText()};
            System.out.println(db.queryInsert("ancienstock", colon, inf));
            JOptionPane.showMessageDialog(this, "Ajout avec succes");
            table();
            actualiser();
        }
    }//GEN-LAST:event_btn_insererActionPerformed

    private void txt_idTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idTelActionPerformed

    private void btnJtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJtableActionPerformed
        Affectation AF= new Affectation();
        AF.setVisible(true);
        this.setVisible(true);
        
        Affectation.txt_idtel.setText(txt_idTel.getText());
       Affectation.txt_type.setText(txt_typeA.getText());
       Affectation.txt_ns.setText(txt_numS.getText());
       Affectation.txt_am.setText(txt_addM.getText());
       
      
      
    }//GEN-LAST:event_btnJtableActionPerformed

    private void btn_ExportExclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExportExclActionPerformed
        JFileChooser fc = new JFileChooser();
                int option = fc.showSaveDialog(AncienStock.this);
                if(option == JFileChooser.APPROVE_OPTION){
                    String filename = fc.getSelectedFile().getName(); 
                    String path = fc.getSelectedFile().getParentFile().getPath();

					int len = filename.length();
					String ext = "";
					String file = "";

					if(len > 4){
						ext = filename.substring(len-4, len);
					}

					if(ext.equals(".xls")){
						file = path + "\\" + filename; 
					}else{
						file = path + "\\" + filename + ".xls"; 
					}
					toExcel(TableAncienStock, new File(file));
                                        JOptionPane.showMessageDialog(null, "Ficher Excel Exporté avec Succés à "+path+"");
				}
    }//GEN-LAST:event_btn_ExportExclActionPerformed

    private void btn_TaffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaffeActionPerformed
        Fonct AF= new Fonct();
        AF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_TaffeActionPerformed

    private void btn_ExportPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExportPdfActionPerformed
      MessageFormat header =new MessageFormat("rapport ");
      MessageFormat footer =new MessageFormat("Page{0,number,Integer} ");
       try{
           TableAncienStock.print(JTable.PrintMode.FIT_WIDTH,header,footer);
           JOptionPane.showMessageDialog(null,"Impression avec succés ");
      }catch(java.awt.print.PrinterException e){
          JOptionPane.showMessageDialog(null,"Erreur Impression "+e+"");
      
      }
    }//GEN-LAST:event_btn_ExportPdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AncienStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AncienStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AncienStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AncienStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AncienStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableAncienStock;
    private javax.swing.JButton btnJtable;
    private javax.swing.JButton btn_ExportExcl;
    private javax.swing.JButton btn_ExportPdf;
    private javax.swing.JButton btn_Taffe;
    private javax.swing.JButton btn_inserer;
    private javax.swing.JButton btn_retour;
    private javax.swing.JButton btn_supprimer;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel laAs;
    private javax.swing.JTextField txt_addM;
    private javax.swing.JTextField txt_idTel;
    private javax.swing.JTextField txt_numS;
    private javax.swing.JTextField txt_typeA;
    // End of variables declaration//GEN-END:variables

   
