
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yassine
 */
public class AncienStock1 extends javax.swing.JFrame {

    /**
     * Creates new form AncienStock1
     */
    public AncienStock1() {
        initComponents();
        getContentPane().setBackground(Color.white);
        setTitle("Ancien Stock");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_aj = new javax.swing.JButton();
        btn_imprimer_etat1 = new javax.swing.JButton();
        btn_cons_stock = new javax.swing.JButton();
        btn_cons_stock1 = new javax.swing.JButton();
        btn_imprimer_etat = new javax.swing.JButton();
        btn_modifier_stock = new javax.swing.JButton();
        la_as = new javax.swing.JLabel();
        btn_quitter1 = new javax.swing.JButton();
        btn_retour = new javax.swing.JButton();
        btn_Taffe = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1009, 612));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_aj.setBackground(new java.awt.Color(67, 174, 76));
        btn_aj.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Ajouter.png")); // NOI18N
        btn_aj.setText("Ajouter Téléphone");
        btn_aj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajActionPerformed(evt);
            }
        });
        getContentPane().add(btn_aj, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 185, 52));

        btn_imprimer_etat1.setBackground(new java.awt.Color(67, 174, 76));
        btn_imprimer_etat1.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\PDF.png")); // NOI18N
        btn_imprimer_etat1.setText("Imprimer Etat");
        btn_imprimer_etat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimer_etat1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_imprimer_etat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 185, 52));

        btn_cons_stock.setBackground(new java.awt.Color(67, 174, 76));
        btn_cons_stock.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\consulter.png")); // NOI18N
        btn_cons_stock.setText("Consulter Stock");
        btn_cons_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cons_stockActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cons_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 185, 52));

        btn_cons_stock1.setBackground(new java.awt.Color(67, 174, 76));
        btn_cons_stock1.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Search.png")); // NOI18N
        btn_cons_stock1.setText("Rechercher");
        btn_cons_stock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cons_stock1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cons_stock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 185, 52));

        btn_imprimer_etat.setBackground(new java.awt.Color(67, 174, 76));
        btn_imprimer_etat.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\statistics.png")); // NOI18N
        btn_imprimer_etat.setText("Consulter Statistique");
        btn_imprimer_etat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimer_etatActionPerformed(evt);
            }
        });
        getContentPane().add(btn_imprimer_etat, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 185, 52));

        btn_modifier_stock.setBackground(new java.awt.Color(67, 174, 76));
        btn_modifier_stock.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\editer.png")); // NOI18N
        btn_modifier_stock.setText("Modifier Stock");
        btn_modifier_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_stockActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modifier_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 185, 52));

        la_as.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        la_as.setForeground(new java.awt.Color(67, 174, 76));
        la_as.setText("Ancien Stock");
        getContentPane().add(la_as, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 25));

        btn_quitter1.setBackground(new java.awt.Color(67, 174, 76));
        btn_quitter1.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\quitter.png")); // NOI18N
        btn_quitter1.setText("Quitter");
        btn_quitter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitter1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_quitter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 185, 52));

        btn_retour.setBackground(new java.awt.Color(67, 174, 76));
        btn_retour.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Back.png")); // NOI18N
        btn_retour.setText("Retour");
        btn_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retourActionPerformed(evt);
            }
        });
        getContentPane().add(btn_retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 185, 52));

        btn_Taffe.setBackground(new java.awt.Color(67, 174, 76));
        btn_Taffe.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Home-.png")); // NOI18N
        btn_Taffe.setText("Accueil");
        btn_Taffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaffeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Taffe, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 180, 56));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cons_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cons_stockActionPerformed
        this.setVisible(false);
        AncienStock a=new AncienStock();
        a.setVisible(true);
    }//GEN-LAST:event_btn_cons_stockActionPerformed

    private void btn_imprimer_etatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimer_etatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imprimer_etatActionPerformed

    private void btn_modifier_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_stockActionPerformed
        this.setVisible(false);
        AncienStock a=new AncienStock();
        a.setVisible(true);
    }//GEN-LAST:event_btn_modifier_stockActionPerformed

    private void btn_ajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AjouterTelAncienStock a=new  AjouterTelAncienStock();
        a.setVisible(true);
    }//GEN-LAST:event_btn_ajActionPerformed

    private void btn_imprimer_etat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimer_etat1ActionPerformed
       this.setVisible(false);
        AncienStock a=new  AncienStock();
        a.setVisible(true);
    }//GEN-LAST:event_btn_imprimer_etat1ActionPerformed

    private void btn_cons_stock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cons_stock1ActionPerformed
        this.setVisible(false);
        AncienStock a=new AncienStock();
        a.setVisible(true);
    }//GEN-LAST:event_btn_cons_stock1ActionPerformed

    private void btn_quitter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitter1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_quitter1ActionPerformed

    private void btn_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retourActionPerformed
        this.setVisible(false);
        Fonct f=new Fonct();
        f.setVisible(true);
    }//GEN-LAST:event_btn_retourActionPerformed

    private void btn_TaffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaffeActionPerformed
        Fonct AF= new Fonct();
        AF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_TaffeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AncienStock1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AncienStock1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AncienStock1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AncienStock1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AncienStock1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Taffe;
    private javax.swing.JButton btn_aj;
    private javax.swing.JButton btn_cons_stock;
    private javax.swing.JButton btn_cons_stock1;
    private javax.swing.JButton btn_imprimer_etat;
    private javax.swing.JButton btn_imprimer_etat1;
    private javax.swing.JButton btn_modifier_stock;
    private javax.swing.JButton btn_quitter1;
    private javax.swing.JButton btn_retour;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel la_as;
    // End of variables declaration//GEN-END:variables
}
