
import BDD.BDD;
import BDD.Parameter;
import BDD.ResultSetTableModel;
import java.awt.Color;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yassine
 */
public class DernierArrivage extends javax.swing.JFrame {
    
    MysqlConnect  maConnexion=new MysqlConnect();
  
    
   /*
   PreparedStatement=null;*/
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    Statement stat=null;
    // ResultSet rs;
    BDD db;

    /**
     * Creates new form DernierArrivage
     */
    private  void update_table ()throws SQLException{
      rs=stat.executeQuery("select * from dernierarr");
       TableDernierArrivage.setModel(DbUtils.resultSetToTableModel(rs));
    
}
    public DernierArrivage() {
        initComponents();
        db = new BDD(new Parameter().HOST_DB, new Parameter().USERNAME_DB, new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
        setTitle("Dernier Arrivage");
        getContentPane().setBackground(Color.white);
        
  DefaultTableModel model= new DefaultTableModel();
   model.addColumn("idS1");
   model.addColumn("typeApp");
   model.addColumn("Nserie");
   model.addColumn("AdresseM");
   
   
   TableDernierArrivage.setModel(model);
   String requette="select * from dernierarr";
    
  try{
      
      stat=MysqlConnect.ConnectDB().createStatement();
        ResultSet rs=stat.executeQuery(requette);
        while(rs.next()){
        model.addRow(new Object[]{rs.getInt("idS1"),rs.getString("typeApp"),rs.getString("Nserie"),rs.getString("AdresseM")} );
        }
         
   }catch(SQLException ex){
       JOptionPane.showMessageDialog(null, ex);
   }   
   };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     public void table() {
        String t[] = {"idS1","typeApp","Nserie","AdresseM"};
        rs = db.querySelect(t, "dernierarr");
        TableDernierArrivage.setModel(new ResultSetTableModel(rs));
    }
     void actualiser() {
        txt_idS1.setText("");
        txt_typeApp.setText("");
        txt_Nserie.setText("");
        txt_AdresseM.setText("");}
   
    
    
    public void toExcel(JTable table, File file){
		try{
			TableModel model = table.getModel();
			FileWriter excel = new FileWriter(file);

			for(int i = 0; i < model.getColumnCount(); i++){
				excel.write(model.getColumnName(i) + "\t");
			}

			excel.write("\n");

			for(int i=0; i< model.getRowCount(); i++) {
				for(int j=0; j < model.getColumnCount(); j++) {
					excel.write(model.getValueAt(i,j).toString()+"\t");
				}
				excel.write("\n");
			}

			excel.close();
		}catch(IOException e){ System.out.println(e); }
	}

	
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_ajouter = new javax.swing.JButton();
        btn_modifier = new javax.swing.JButton();
        btn_print = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDernierArrivage = new javax.swing.JTable();
        btn_exporter = new javax.swing.JButton();
        btn_supprimer1 = new javax.swing.JButton();
        btn_retour = new javax.swing.JButton();
        btn_Affecter = new javax.swing.JButton();
        btn_Taffe = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txt_Nserie = new javax.swing.JTextField();
        txt_typeApp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_AdresseM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_idS1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(67, 174, 76));
        jLabel1.setText("Dernier Arrivage");

        btn_ajouter.setBackground(new java.awt.Color(67, 147, 76));
        btn_ajouter.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Ajouter.png")); // NOI18N
        btn_ajouter.setText("Ajouter");
        btn_ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajouterActionPerformed(evt);
            }
        });

        btn_modifier.setBackground(new java.awt.Color(67, 147, 76));
        btn_modifier.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\editer.png")); // NOI18N
        btn_modifier.setText("Modifier");
        btn_modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifierActionPerformed(evt);
            }
        });

        btn_print.setBackground(new java.awt.Color(67, 147, 76));
        btn_print.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\PDF2.png")); // NOI18N
        btn_print.setText("Exporter PDF");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        TableDernierArrivage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableDernierArrivage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDernierArrivageMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableDernierArrivage);

        btn_exporter.setBackground(new java.awt.Color(67, 147, 76));
        btn_exporter.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Excel.png")); // NOI18N
        btn_exporter.setText("Exporter Excel");
        btn_exporter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exporterActionPerformed(evt);
            }
        });

        btn_supprimer1.setBackground(new java.awt.Color(67, 147, 76));
        btn_supprimer1.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\poubelle.png")); // NOI18N
        btn_supprimer1.setText("Supprimer");
        btn_supprimer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supprimer1ActionPerformed(evt);
            }
        });

        btn_retour.setBackground(new java.awt.Color(67, 147, 76));
        btn_retour.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Back.png")); // NOI18N
        btn_retour.setText("Retour");
        btn_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retourActionPerformed(evt);
            }
        });

        btn_Affecter.setBackground(new java.awt.Color(67, 147, 76));
        btn_Affecter.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\transfrer.png")); // NOI18N
        btn_Affecter.setText("Affecter");
        btn_Affecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AffecterActionPerformed(evt);
            }
        });

        btn_Taffe.setBackground(new java.awt.Color(67, 147, 76));
        btn_Taffe.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Home-.png")); // NOI18N
        btn_Taffe.setText("Accueil");
        btn_Taffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaffeActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 174, 76), 2));

        jLabel3.setText("typeApp");

        jLabel4.setText("Num Serie");

        jLabel2.setText("idTel");

        jLabel5.setText("Adresse Mac");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_idS1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_typeApp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Nserie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_AdresseM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txt_idS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_typeApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Nserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_AdresseM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btn_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(btn_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btn_supprimer1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btn_Taffe, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(btn_Affecter, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_exporter)
                                .addGap(18, 18, 18)
                                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_supprimer1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Affecter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_exporter, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Taffe, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableDernierArrivageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDernierArrivageMouseClicked
         txt_idS1.setText(String.valueOf(TableDernierArrivage.getValueAt(TableDernierArrivage.getSelectedRow(),0)));
       txt_typeApp.setText(String.valueOf(TableDernierArrivage.getValueAt(TableDernierArrivage.getSelectedRow(), 1)));
       txt_Nserie.setText(String.valueOf(TableDernierArrivage.getValueAt(TableDernierArrivage.getSelectedRow(),2)));
       txt_AdresseM.setText(String.valueOf(TableDernierArrivage.getValueAt(TableDernierArrivage.getSelectedRow(),3)));
        
    }//GEN-LAST:event_TableDernierArrivageMouseClicked

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
     
      
      MessageFormat header =new MessageFormat("rapport ");
      MessageFormat footer =new MessageFormat("Page{0,number,Integer} ");
       try{
           TableDernierArrivage.print(JTable.PrintMode.FIT_WIDTH,header,footer);
      }catch(java.awt.print.PrinterException e){
          JOptionPane.showMessageDialog(null,"Erreur Impression al3chir"+e+"");
      
      }
        
        
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajouterActionPerformed
        if (txt_idS1.getText().equals("") ||txt_typeApp.getText().equals("") || txt_Nserie.getText().equals("")
                || txt_AdresseM.getText().equals("") 
                ) {
            JOptionPane.showMessageDialog(this, "Veuillez Remplir tous les champs");
        } else {
            String[] colon = {"idS1","typeApp","Nserie","AdresseM"};
            String[] inf = {txt_idS1.getText(), txt_typeApp.getText(), txt_Nserie.getText(),txt_AdresseM.getText()};
            System.out.println(db.queryInsert("ancienstock", colon, inf));
            JOptionPane.showMessageDialog(this, "Ajout avec succès");
            table();
            actualiser();
        }
    }//GEN-LAST:event_btn_ajouterActionPerformed

    private void btn_exporterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exporterActionPerformed
        
       /* 
        if(this.TableDernierArrivage.getRowCount()==0){
        JOptionPane.showMessageDialog(null, "no exportar datos in jtable", "invertissement", JOptionPane.INFORMATION_MESSAGE);
        this.txt_export.grabFocus();
        return;
        }
        
        JFileChooser chooser=new JFileChooser();
        //FileNameExtentionFilter filter =new FileNameExtentionFilter("archivo en excel",".xls");
        FileNameExtensionFilter filter=new FileNameExtensionFilter("Fichier Excel",".xls");
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Exporter Excel");
        chooser.setMultiSelectionEnabled(false);
        chooser.setAcceptAllFileFilterUsed(false);
        if(chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){
            JOptionPane.showMessageDialog(null, "ha errror alalwal");
                 List<JTable> tb=new ArrayList<>();
        List <String >non=new ArrayList<>();
        tb.add(TableDernierArrivage);
        non.add("socios");
        String file=chooser.getSelectedFile().toString().concat(".xls");
        
        try{
       Exporter e=new Exporter(new File(file),tb,non);
        if(e.export()){
        JOptionPane.showMessageDialog(null, "jopo2 m3art");
        
        }
        }catch(Exception e){
        
        JOptionPane.showMessageDialog(null, "errooro");
        
        }
        
        
        
        }*/
                  JFileChooser fc = new JFileChooser();
                int option = fc.showSaveDialog(DernierArrivage.this);
                if(option == JFileChooser.APPROVE_OPTION){
                    String filename = fc.getSelectedFile().getName(); 
                    String path = fc.getSelectedFile().getParentFile().getPath();

					int len = filename.length();
					String ext = "";
					String file = "";

					if(len > 4){
						ext = filename.substring(len-4, len);
					}

					if(ext.equals(".xls")){
						file = path + "\\" + filename; 
					}else{
						file = path + "\\" + filename + ".xls"; 
					}
					toExcel(TableDernierArrivage, new File(file));
                                        JOptionPane.showMessageDialog(null, "Ficher Excel Exporté avec Succés à "+path+"");
				}
                
                
    }//GEN-LAST:event_btn_exporterActionPerformed

    private void btn_modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifierActionPerformed
       if (txt_idS1.getText().equals("") ||txt_typeApp.getText().equals("") || txt_Nserie.getText().equals("")
                || txt_AdresseM.getText().equals("") 
                ) {
            JOptionPane.showMessageDialog(this, "SVP entrer les informations complete");
        } else {
            String[] colon = {"idS1","typeApp","Nserie","AdresseM"};
            String[] inf = {txt_idS1.getText(), txt_typeApp.getText(),  txt_Nserie.getText(),txt_AdresseM.getText()};
            String idS = String.valueOf(TableDernierArrivage.getValueAt(TableDernierArrivage.getSelectedRow(),0));
            System.out.println(db.queryUpdate("dernierarr", colon, inf, "idS1='"+ idS+"'"));
            JOptionPane.showMessageDialog(this, "Modifié avec succès");
            table();
            actualiser();
        }

    }//GEN-LAST:event_btn_modifierActionPerformed
  
    private void btn_supprimer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supprimer1ActionPerformed
String id = String.valueOf(TableDernierArrivage.getValueAt(TableDernierArrivage.getSelectedRow(),0));
        if (JOptionPane.showConfirmDialog(this, "Voulez vraiment suprimer!!"," Avertissement", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            db.queryDelete("dernierarr", "idS1="+ id);
        } else {
            return;
        }
        table();
        actualiser();
                 
    }//GEN-LAST:event_btn_supprimer1ActionPerformed

    private void btn_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retourActionPerformed
       this.setVisible(false);
       AncienStock1 a=new AncienStock1();
       a.setVisible(true);
    }//GEN-LAST:event_btn_retourActionPerformed

    private void btn_AffecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AffecterActionPerformed
       
         Affectation AF= new Affectation();
        AF.setVisible(true);
        this.setVisible(false);
        
       
        
        Affectation.txt_idtel.setText(txt_idS1.getText());
       Affectation.txt_type.setText(txt_typeApp.getText());
       Affectation.txt_ns.setText(txt_Nserie.getText());
       Affectation.txt_am.setText(txt_AdresseM.getText());
    }//GEN-LAST:event_btn_AffecterActionPerformed

    private void btn_TaffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaffeActionPerformed
        Fonct AF= new Fonct();
        AF.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_TaffeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DernierArrivage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DernierArrivage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DernierArrivage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DernierArrivage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DernierArrivage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableDernierArrivage;
    private javax.swing.JButton btn_Affecter;
    private javax.swing.JButton btn_Taffe;
    private javax.swing.JButton btn_ajouter;
    private javax.swing.JButton btn_exporter;
    private javax.swing.JButton btn_modifier;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_retour;
    private javax.swing.JButton btn_supprimer1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_AdresseM;
    private javax.swing.JTextField txt_Nserie;
    private javax.swing.JTextField txt_idS1;
    private javax.swing.JTextField txt_typeApp;
    // End of variables declaration//GEN-END:variables

    
}
