
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yassine
 */
public class DernierArrivage1 extends javax.swing.JFrame {

    /**
     * Creates new form Stock_Modifier_Stock
     */
    public DernierArrivage1() {
        initComponents();
        getContentPane().setBackground(Color.white);
        setTitle("Dernier Arrivage");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        la_cs = new javax.swing.JLabel();
        btn_aj = new javax.swing.JButton();
        btn_imprimer_etat1 = new javax.swing.JButton();
        btn_cons_stock = new javax.swing.JButton();
        btn_cons_stock1 = new javax.swing.JButton();
        btn_imprimer_etat = new javax.swing.JButton();
        btn_modifier_stock = new javax.swing.JButton();
        btn_retour = new javax.swing.JButton();
        btn_quitter1 = new javax.swing.JButton();
        btn_Taffe1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        la_cs.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        la_cs.setForeground(new java.awt.Color(67, 174, 76));
        la_cs.setText("Dernier Arrivage");

        btn_aj.setBackground(new java.awt.Color(67, 174, 76));
        btn_aj.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Ajouter.png")); // NOI18N
        btn_aj.setText("Ajouter Téléphone");
        btn_aj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ajActionPerformed(evt);
            }
        });

        btn_imprimer_etat1.setBackground(new java.awt.Color(67, 174, 76));
        btn_imprimer_etat1.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\PDF2.png")); // NOI18N
        btn_imprimer_etat1.setText("Imprimer Etat");

        btn_cons_stock.setBackground(new java.awt.Color(67, 174, 76));
        btn_cons_stock.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\consulter.png")); // NOI18N
        btn_cons_stock.setText("Consulter Stock");
        btn_cons_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cons_stockActionPerformed(evt);
            }
        });

        btn_cons_stock1.setBackground(new java.awt.Color(67, 174, 76));
        btn_cons_stock1.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Search.png")); // NOI18N
        btn_cons_stock1.setText("Rechercher");

        btn_imprimer_etat.setBackground(new java.awt.Color(67, 174, 76));
        btn_imprimer_etat.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\statistics.png")); // NOI18N
        btn_imprimer_etat.setText("Consulter Statistique");
        btn_imprimer_etat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimer_etatActionPerformed(evt);
            }
        });

        btn_modifier_stock.setBackground(new java.awt.Color(67, 174, 76));
        btn_modifier_stock.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\editer.png")); // NOI18N
        btn_modifier_stock.setText("Modifier Stock");
        btn_modifier_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifier_stockActionPerformed(evt);
            }
        });

        btn_retour.setBackground(new java.awt.Color(67, 174, 76));
        btn_retour.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Back.png")); // NOI18N
        btn_retour.setText("Retour");
        btn_retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retourActionPerformed(evt);
            }
        });

        btn_quitter1.setBackground(new java.awt.Color(67, 174, 76));
        btn_quitter1.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\quitter.png")); // NOI18N
        btn_quitter1.setText("Quitter");
        btn_quitter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitter1ActionPerformed(evt);
            }
        });

        btn_Taffe1.setBackground(new java.awt.Color(67, 174, 76));
        btn_Taffe1.setIcon(new javax.swing.ImageIcon("C:\\Program Files\\NetBeans 8.0.2\\icons\\Home-.png")); // NOI18N
        btn_Taffe1.setText("Accueil");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cons_stock1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aj, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_imprimer_etat1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                                .addComponent(btn_cons_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_imprimer_etat, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_quitter1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_Taffe1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_modifier_stock, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))))
                        .addGap(171, 171, 171))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(la_cs)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(la_cs, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cons_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_imprimer_etat1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aj, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_imprimer_etat, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modifier_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cons_stock1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_retour, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_quitter1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Taffe1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(153, 186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ajActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AjouterAuDernierArr a=new AjouterAuDernierArr();
        a.setVisible(true);

    }//GEN-LAST:event_btn_ajActionPerformed

    private void btn_cons_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cons_stockActionPerformed
        this.setVisible(false);
        DernierArrivage a=new DernierArrivage();
        a.setVisible(true);
    }//GEN-LAST:event_btn_cons_stockActionPerformed

    private void btn_imprimer_etatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimer_etatActionPerformed
        this.setVisible(false);
        DernierArrivage a=new DernierArrivage();
        a.setVisible(true);
    }//GEN-LAST:event_btn_imprimer_etatActionPerformed

    private void btn_modifier_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifier_stockActionPerformed
        this.setVisible(false);
        DernierArrivage a=new DernierArrivage();
        a.setVisible(true);
    }//GEN-LAST:event_btn_modifier_stockActionPerformed

    private void btn_retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retourActionPerformed
        this.setVisible(false);
        Fonct f=new Fonct();
        f.setVisible(true);
    }//GEN-LAST:event_btn_retourActionPerformed

    private void btn_quitter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitter1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_quitter1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock_Modifier_Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock_Modifier_Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock_Modifier_Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock_Modifier_Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 DernierArrivage1 a=new DernierArrivage1();
               a.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Taffe1;
    private javax.swing.JButton btn_aj;
    private javax.swing.JButton btn_cons_stock;
    private javax.swing.JButton btn_cons_stock1;
    private javax.swing.JButton btn_imprimer_etat;
    private javax.swing.JButton btn_imprimer_etat1;
    private javax.swing.JButton btn_modifier_stock;
    private javax.swing.JButton btn_quitter1;
    private javax.swing.JButton btn_retour;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel la_cs;
    // End of variables declaration//GEN-END:variables
}
